# Generated by Django 3.1.7 on 2021-03-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
