# Generated by Django 3.1.7 on 2021-03-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesdata',
            old_name='description',
            new_name='about',
        ),
    ]
