# Generated by Django 3.1.7 on 2021-03-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210307_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesdata',
            name='image',
            field=models.ImageField(default='Images/None/noimg.jpg', upload_to='Images/'),
        ),
    ]
